# Generated by Django 4.2 on 2024-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified_user_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content_manager',
            field=models.BooleanField(default=False, verbose_name='Контент-менеджер'),
        ),
    ]
