# Generated by Django 5.0.1 on 2024-02-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='slug'),
        ),
    ]
